# Copyright (c) 2026 RAKwireless Technology Limited
# SPDX-License-Identifier: Apache-2.0

manifest:

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      repo-path: zephyr
      revision: v4.3.0
      # Only modules required to build RAK3162 samples/hw_test
      # (nRF54L15 + LoRaWAN loramac-node + onboard SX1262).
      import:
        name-allowlist:
          - cmsis_6
          - cmsis
          - hal_nordic
          - loramac-node

  self:
    path: rak3162-zephyr-bsp
